// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DiscoverModels(arg1) {
  return window['go']['discovery']['Service']['DiscoverModels'](arg1);
}

export function TestConnectivity(arg1) {
  return window['go']['discovery']['Service']['TestConnectivity'](arg1);
}
