// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {discovery} from '../models';

export function DiscoverModels(arg1:string):Promise<Array<discovery.DiscoveredModel>>;

export function TestConnectivity(arg1:string):Promise<boolean>;
