// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {presets} from '../models';

export function Count():Promise<number>;

export function GetByName(arg1:string):Promise<presets.ProviderPreset>;

export function ImportCustom(arg1:Array<number>):Promise<void>;

export function ListByCategory(arg1:string):Promise<Array<presets.ProviderPreset>>;

export function ListByRegion(arg1:string):Promise<Array<presets.ProviderPreset>>;

export function ListPresets():Promise<Array<presets.ProviderPreset>>;
