// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Count() {
  return window['go']['presets']['Service']['Count']();
}

export function GetByName(arg1) {
  return window['go']['presets']['Service']['GetByName'](arg1);
}

export function ImportCustom(arg1) {
  return window['go']['presets']['Service']['ImportCustom'](arg1);
}

export function ListByCategory(arg1) {
  return window['go']['presets']['Service']['ListByCategory'](arg1);
}

export function ListByRegion(arg1) {
  return window['go']['presets']['Service']['ListByRegion'](arg1);
}

export function ListPresets() {
  return window['go']['presets']['Service']['ListPresets']();
}
