// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateByokPolicy(arg1) {
  return window['go']['auth']['Service']['CreateByokPolicy'](arg1);
}

export function DeleteCloudCombo(arg1) {
  return window['go']['auth']['Service']['DeleteCloudCombo'](arg1);
}

export function FetchActiveGrants() {
  return window['go']['auth']['Service']['FetchActiveGrants']();
}

export function FetchByokPolicies() {
  return window['go']['auth']['Service']['FetchByokPolicies']();
}

export function FetchCloudBilling() {
  return window['go']['auth']['Service']['FetchCloudBilling']();
}

export function FetchCloudCombos() {
  return window['go']['auth']['Service']['FetchCloudCombos']();
}

export function FetchCloudModelStats() {
  return window['go']['auth']['Service']['FetchCloudModelStats']();
}

export function FetchCloudOptimizationConfig() {
  return window['go']['auth']['Service']['FetchCloudOptimizationConfig']();
}

export function FetchCloudUsage() {
  return window['go']['auth']['Service']['FetchCloudUsage']();
}

export function FetchEnterpriseChannels(arg1) {
  return window['go']['auth']['Service']['FetchEnterpriseChannels'](arg1);
}

export function FetchFreeChannels(arg1) {
  return window['go']['auth']['Service']['FetchFreeChannels'](arg1);
}

export function FetchModelCatalog(arg1) {
  return window['go']['auth']['Service']['FetchModelCatalog'](arg1);
}

export function FetchOfficialComboTemplates(arg1) {
  return window['go']['auth']['Service']['FetchOfficialComboTemplates'](arg1);
}

export function FetchPlans() {
  return window['go']['auth']['Service']['FetchPlans']();
}

export function FetchPlatformChannels(arg1) {
  return window['go']['auth']['Service']['FetchPlatformChannels'](arg1);
}

export function FetchProviderHealthMetrics(arg1) {
  return window['go']['auth']['Service']['FetchProviderHealthMetrics'](arg1);
}

export function FetchProviderHealthSummary() {
  return window['go']['auth']['Service']['FetchProviderHealthSummary']();
}

export function FetchRecommendedCombos() {
  return window['go']['auth']['Service']['FetchRecommendedCombos']();
}

export function GetAuthState() {
  return window['go']['auth']['Service']['GetAuthState']();
}

export function GetPlatformToken() {
  return window['go']['auth']['Service']['GetPlatformToken']();
}

export function IsLoggedIn() {
  return window['go']['auth']['Service']['IsLoggedIn']();
}

export function Login(arg1, arg2) {
  return window['go']['auth']['Service']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['auth']['Service']['Logout']();
}

export function PlatformAPIBaseURL() {
  return window['go']['auth']['Service']['PlatformAPIBaseURL']();
}

export function PushCloudCombo(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['auth']['Service']['PushCloudCombo'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function PushCloudOptimizationConfig(arg1) {
  return window['go']['auth']['Service']['PushCloudOptimizationConfig'](arg1);
}

export function Register(arg1, arg2, arg3) {
  return window['go']['auth']['Service']['Register'](arg1, arg2, arg3);
}

export function SyncCloudCombosToLocal() {
  return window['go']['auth']['Service']['SyncCloudCombosToLocal']();
}

export function UpdateCloudCombo(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['auth']['Service']['UpdateCloudCombo'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}
