// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {auth} from '../models';
import {context} from '../models';

export function CreateByokPolicy(arg1:Record<string, any>):Promise<Record<string, any>>;

export function DeleteCloudCombo(arg1:string):Promise<void>;

export function DoPlatformRequest(arg1:string,arg2:string,arg3:Array<number>):Promise<number>;

export function FetchActiveGrants():Promise<Array<auth.ActiveGrant>>;

export function FetchByokPolicies():Promise<Array<Record<string, any>>>;

export function FetchCloudBilling():Promise<auth.CloudBilling>;

export function FetchCloudCombos():Promise<Array<auth.CloudUserCombo>>;

export function FetchCloudModelStats():Promise<Array<auth.CloudModelStatsEntry>>;

export function FetchCloudOptimizationConfig():Promise<string>;

export function FetchCloudUsage():Promise<auth.CloudUsage>;

export function FetchEnterpriseChannels(arg1:context.Context):Promise<Array<Record<string, any>>>;

export function FetchFreeChannels(arg1:context.Context):Promise<Array<Record<string, any>>>;

export function FetchModelCatalog(arg1:context.Context):Promise<Array<Record<string, any>>>;

export function FetchModelIndex(arg1:context.Context,arg2:string):Promise<Record<string, any>>;

export function FetchOAuthProviders():Promise<Array<auth.OAuthProvider>>;

export function FetchOfficialComboTemplates(arg1:context.Context):Promise<Array<auth.CloudComboTemplate>>;

export function FetchOverageUsage():Promise<auth.OverageUsage>;

export function FetchPlans():Promise<Array<auth.CloudPlan>>;

export function FetchPlatformChannels(arg1:context.Context):Promise<Array<Record<string, any>>>;

export function FetchProviderHealthMetrics(arg1:string):Promise<Array<Record<string, any>>>;

export function FetchProviderHealthSummary():Promise<Array<Record<string, any>>>;

export function FetchRecommendedCombos():Promise<Array<auth.CloudCombo>>;

export function GetAuthState():Promise<auth.AuthInfo>;

export function GetPlatformToken():Promise<string>;

export function IsLoggedIn():Promise<boolean>;

export function Login(arg1:string,arg2:string):Promise<void>;

export function Logout():Promise<void>;

export function PlatformAPIBaseURL():Promise<string>;

export function PushCloudCombo(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:string,arg7:Record<string, any>,arg8:Array<number>):Promise<auth.CloudUserCombo>;

export function PushCloudOptimizationConfig(arg1:string):Promise<void>;

export function Register(arg1:string,arg2:string,arg3:string):Promise<void>;

export function StartOAuthLogin(arg1:string):Promise<void>;

export function SyncCloudCombosToLocal():Promise<Array<auth.CloudUserCombo>>;

export function UpdateCloudCombo(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:string,arg7:string,arg8:Record<string, any>,arg9:Array<number>):Promise<void>;
