// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {mcp} from '../models';

export function DeleteServer(arg1:string):Promise<void>;

export function ListServers():Promise<Array<mcp.MCPServer>>;

export function SaveServer(arg1:mcp.MCPServer):Promise<void>;

export function ToggleServer(arg1:string,arg2:boolean):Promise<void>;
