// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteServer(arg1) {
  return window['go']['mcp']['Service']['DeleteServer'](arg1);
}

export function ListServers() {
  return window['go']['mcp']['Service']['ListServers']();
}

export function SaveServer(arg1) {
  return window['go']['mcp']['Service']['SaveServer'](arg1);
}

export function ToggleServer(arg1, arg2) {
  return window['go']['mcp']['Service']['ToggleServer'](arg1, arg2);
}
