// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMITMRule(arg1) {
  return window['go']['main']['App']['AddMITMRule'](arg1);
}

export function ApplyComboOptimization(arg1, arg2, arg3) {
  return window['go']['main']['App']['ApplyComboOptimization'](arg1, arg2, arg3);
}

export function ApplyComboSortPreset(arg1, arg2) {
  return window['go']['main']['App']['ApplyComboSortPreset'](arg1, arg2);
}

export function ApplyPromptPreset(arg1, arg2) {
  return window['go']['main']['App']['ApplyPromptPreset'](arg1, arg2);
}

export function ApplyRecommendation(arg1, arg2) {
  return window['go']['main']['App']['ApplyRecommendation'](arg1, arg2);
}

export function ChatCompletion(arg1, arg2) {
  return window['go']['main']['App']['ChatCompletion'](arg1, arg2);
}

export function ChatCompletionForChannel(arg1, arg2, arg3) {
  return window['go']['main']['App']['ChatCompletionForChannel'](arg1, arg2, arg3);
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function ClearSelectedGrant() {
  return window['go']['main']['App']['ClearSelectedGrant']();
}

export function ConfirmAction(arg1, arg2) {
  return window['go']['main']['App']['ConfirmAction'](arg1, arg2);
}

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function CreateCheckoutSession(arg1, arg2) {
  return window['go']['main']['App']['CreateCheckoutSession'](arg1, arg2);
}

export function CreateEvalSuite(arg1) {
  return window['go']['main']['App']['CreateEvalSuite'](arg1);
}

export function DeleteCloudCombo(arg1) {
  return window['go']['main']['App']['DeleteCloudCombo'](arg1);
}

export function DeleteComboTemplate(arg1) {
  return window['go']['main']['App']['DeleteComboTemplate'](arg1);
}

export function DeleteCustomChannel(arg1) {
  return window['go']['main']['App']['DeleteCustomChannel'](arg1);
}

export function DeleteMCPServer(arg1) {
  return window['go']['main']['App']['DeleteMCPServer'](arg1);
}

export function DeleteModelCombo(arg1) {
  return window['go']['main']['App']['DeleteModelCombo'](arg1);
}

export function DeletePromptPreset(arg1, arg2) {
  return window['go']['main']['App']['DeletePromptPreset'](arg1, arg2);
}

export function DeleteSession(arg1, arg2) {
  return window['go']['main']['App']['DeleteSession'](arg1, arg2);
}

export function DiscoverModels(arg1) {
  return window['go']['main']['App']['DiscoverModels'](arg1);
}

export function ExchangeOAuthCode(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ExchangeOAuthCode'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ExportConfig() {
  return window['go']['main']['App']['ExportConfig']();
}

export function FetchActiveGrants() {
  return window['go']['main']['App']['FetchActiveGrants']();
}

export function FetchCloudCombos() {
  return window['go']['main']['App']['FetchCloudCombos']();
}

export function FetchEnterpriseChannels() {
  return window['go']['main']['App']['FetchEnterpriseChannels']();
}

export function FetchFreeChannels() {
  return window['go']['main']['App']['FetchFreeChannels']();
}

export function FetchMITMTargetsFromEnterprise() {
  return window['go']['main']['App']['FetchMITMTargetsFromEnterprise']();
}

export function FetchModelCatalog() {
  return window['go']['main']['App']['FetchModelCatalog']();
}

export function FetchModelStats() {
  return window['go']['main']['App']['FetchModelStats']();
}

export function FetchModelsFromURL(arg1, arg2) {
  return window['go']['main']['App']['FetchModelsFromURL'](arg1, arg2);
}

export function GetAppConfig() {
  return window['go']['main']['App']['GetAppConfig']();
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetAuthState() {
  return window['go']['main']['App']['GetAuthState']();
}

export function GetByokPolicies() {
  return window['go']['main']['App']['GetByokPolicies']();
}

export function GetCloudBilling() {
  return window['go']['main']['App']['GetCloudBilling']();
}

export function GetCloudSyncStatus() {
  return window['go']['main']['App']['GetCloudSyncStatus']();
}

export function GetCloudUsage() {
  return window['go']['main']['App']['GetCloudUsage']();
}

export function GetComboByName(arg1) {
  return window['go']['main']['App']['GetComboByName'](arg1);
}

export function GetComboRouteMetrics() {
  return window['go']['main']['App']['GetComboRouteMetrics']();
}

export function GetDailyUsage(arg1) {
  return window['go']['main']['App']['GetDailyUsage'](arg1);
}

export function GetDefaultComboName() {
  return window['go']['main']['App']['GetDefaultComboName']();
}

export function GetEvalScorecard(arg1) {
  return window['go']['main']['App']['GetEvalScorecard'](arg1);
}

export function GetLocalAccessToken() {
  return window['go']['main']['App']['GetLocalAccessToken']();
}

export function GetLocale() {
  return window['go']['main']['App']['GetLocale']();
}

export function GetLogRotationConfig() {
  return window['go']['main']['App']['GetLogRotationConfig']();
}

export function GetMCPAuditLog() {
  return window['go']['main']['App']['GetMCPAuditLog']();
}

export function GetMCPGatewayTools() {
  return window['go']['main']['App']['GetMCPGatewayTools']();
}

export function GetMITMEnvHint() {
  return window['go']['main']['App']['GetMITMEnvHint']();
}

export function GetMITMRecentIntercepts(arg1) {
  return window['go']['main']['App']['GetMITMRecentIntercepts'](arg1);
}

export function GetMITMRules() {
  return window['go']['main']['App']['GetMITMRules']();
}

export function GetMITMStatus() {
  return window['go']['main']['App']['GetMITMStatus']();
}

export function GetMITMTargets() {
  return window['go']['main']['App']['GetMITMTargets']();
}

export function GetOAuthConnections() {
  return window['go']['main']['App']['GetOAuthConnections']();
}

export function GetOAuthProviders() {
  return window['go']['main']['App']['GetOAuthProviders']();
}

export function GetOAuthToken(arg1) {
  return window['go']['main']['App']['GetOAuthToken'](arg1);
}

export function GetOfficialComboTemplates() {
  return window['go']['main']['App']['GetOfficialComboTemplates']();
}

export function GetOptimizationConfig() {
  return window['go']['main']['App']['GetOptimizationConfig']();
}

export function GetOptimizationPlan(arg1, arg2) {
  return window['go']['main']['App']['GetOptimizationPlan'](arg1, arg2);
}

export function GetPerfAuditReport() {
  return window['go']['main']['App']['GetPerfAuditReport']();
}

export function GetPlans() {
  return window['go']['main']['App']['GetPlans']();
}

export function GetPlatformAPIBaseURL() {
  return window['go']['main']['App']['GetPlatformAPIBaseURL']();
}

export function GetPlatformToken() {
  return window['go']['main']['App']['GetPlatformToken']();
}

export function GetPluginAuditLog() {
  return window['go']['main']['App']['GetPluginAuditLog']();
}

export function GetPluginHooks() {
  return window['go']['main']['App']['GetPluginHooks']();
}

export function GetPresetByName(arg1) {
  return window['go']['main']['App']['GetPresetByName'](arg1);
}

export function GetProviderHealthMetrics(arg1) {
  return window['go']['main']['App']['GetProviderHealthMetrics'](arg1);
}

export function GetProviderHealthSummary() {
  return window['go']['main']['App']['GetProviderHealthSummary']();
}

export function GetQuickStrategies() {
  return window['go']['main']['App']['GetQuickStrategies']();
}

export function GetRateLimitConfig() {
  return window['go']['main']['App']['GetRateLimitConfig']();
}

export function GetRecommendedCombos() {
  return window['go']['main']['App']['GetRecommendedCombos']();
}

export function GetRuntimeStatus() {
  return window['go']['main']['App']['GetRuntimeStatus']();
}

export function GetSelectedGrant() {
  return window['go']['main']['App']['GetSelectedGrant']();
}

export function GetSession(arg1, arg2) {
  return window['go']['main']['App']['GetSession'](arg1, arg2);
}

export function GetSessionMessages(arg1, arg2) {
  return window['go']['main']['App']['GetSessionMessages'](arg1, arg2);
}

export function GetSyncConfig() {
  return window['go']['main']['App']['GetSyncConfig']();
}

export function GetSyncStatus() {
  return window['go']['main']['App']['GetSyncStatus']();
}

export function GetTaskProfiles() {
  return window['go']['main']['App']['GetTaskProfiles']();
}

export function GetTotalUsage() {
  return window['go']['main']['App']['GetTotalUsage']();
}

export function GetTunnelStatus() {
  return window['go']['main']['App']['GetTunnelStatus']();
}

export function GetTunnelURL() {
  return window['go']['main']['App']['GetTunnelURL']();
}

export function GetUsageSummary() {
  return window['go']['main']['App']['GetUsageSummary']();
}

export function HandleDeepLink(arg1) {
  return window['go']['main']['App']['HandleDeepLink'](arg1);
}

export function ImageGeneration(arg1, arg2, arg3) {
  return window['go']['main']['App']['ImageGeneration'](arg1, arg2, arg3);
}

export function ImageGenerationForChannel(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ImageGenerationForChannel'](arg1, arg2, arg3, arg4);
}

export function ImportConfig(arg1) {
  return window['go']['main']['App']['ImportConfig'](arg1);
}

export function ImportCustomPreset(arg1) {
  return window['go']['main']['App']['ImportCustomPreset'](arg1);
}

export function InstallSkillFromGitHub(arg1, arg2) {
  return window['go']['main']['App']['InstallSkillFromGitHub'](arg1, arg2);
}

export function InstallSkillFromLocal(arg1, arg2) {
  return window['go']['main']['App']['InstallSkillFromLocal'](arg1, arg2);
}

export function IsMITMRunning() {
  return window['go']['main']['App']['IsMITMRunning']();
}

export function IsTunnelRunning() {
  return window['go']['main']['App']['IsTunnelRunning']();
}

export function ListChannels() {
  return window['go']['main']['App']['ListChannels']();
}

export function ListComboTemplates() {
  return window['go']['main']['App']['ListComboTemplates']();
}

export function ListEvalSuites() {
  return window['go']['main']['App']['ListEvalSuites']();
}

export function ListLogs(arg1, arg2) {
  return window['go']['main']['App']['ListLogs'](arg1, arg2);
}

export function ListLogsFiltered(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['ListLogsFiltered'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function ListMCPServers() {
  return window['go']['main']['App']['ListMCPServers']();
}

export function ListModelCombos() {
  return window['go']['main']['App']['ListModelCombos']();
}

export function ListModelPricing() {
  return window['go']['main']['App']['ListModelPricing']();
}

export function ListPlugins() {
  return window['go']['main']['App']['ListPlugins']();
}

export function ListPresetsByCategory(arg1) {
  return window['go']['main']['App']['ListPresetsByCategory'](arg1);
}

export function ListPromptPresets() {
  return window['go']['main']['App']['ListPromptPresets']();
}

export function ListProviderPresets() {
  return window['go']['main']['App']['ListProviderPresets']();
}

export function ListSessions(arg1, arg2) {
  return window['go']['main']['App']['ListSessions'](arg1, arg2);
}

export function ListSkills() {
  return window['go']['main']['App']['ListSkills']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function OpenInBrowser(arg1) {
  return window['go']['main']['App']['OpenInBrowser'](arg1);
}

export function PerformUpdate() {
  return window['go']['main']['App']['PerformUpdate']();
}

export function PreviewComboOptimization(arg1, arg2) {
  return window['go']['main']['App']['PreviewComboOptimization'](arg1, arg2);
}

export function PushCloudCombo(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['PushCloudCombo'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function ReadCurrentPrompt(arg1) {
  return window['go']['main']['App']['ReadCurrentPrompt'](arg1);
}

export function RecordUsage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['RecordUsage'](arg1, arg2, arg3, arg4, arg5);
}

export function Register(arg1, arg2, arg3) {
  return window['go']['main']['App']['Register'](arg1, arg2, arg3);
}

export function RemoveMITMRule(arg1) {
  return window['go']['main']['App']['RemoveMITMRule'](arg1);
}

export function RenameComboTemplate(arg1, arg2) {
  return window['go']['main']['App']['RenameComboTemplate'](arg1, arg2);
}

export function ReorderChannels(arg1) {
  return window['go']['main']['App']['ReorderChannels'](arg1);
}

export function ResetLocalAccessToken() {
  return window['go']['main']['App']['ResetLocalAccessToken']();
}

export function RevokeOAuthToken(arg1) {
  return window['go']['main']['App']['RevokeOAuthToken'](arg1);
}

export function RunDiagnostics() {
  return window['go']['main']['App']['RunDiagnostics']();
}

export function RunEvalSuite(arg1) {
  return window['go']['main']['App']['RunEvalSuite'](arg1);
}

export function SaveComboTemplate(arg1) {
  return window['go']['main']['App']['SaveComboTemplate'](arg1);
}

export function SaveCustomChannel(arg1) {
  return window['go']['main']['App']['SaveCustomChannel'](arg1);
}

export function SaveMCPServer(arg1) {
  return window['go']['main']['App']['SaveMCPServer'](arg1);
}

export function SaveModelCombo(arg1) {
  return window['go']['main']['App']['SaveModelCombo'](arg1);
}

export function SaveModelPricing(arg1) {
  return window['go']['main']['App']['SaveModelPricing'](arg1);
}

export function SavePromptPreset(arg1) {
  return window['go']['main']['App']['SavePromptPreset'](arg1);
}

export function ScanSkillsDir() {
  return window['go']['main']['App']['ScanSkillsDir']();
}

export function SearchNotion(arg1, arg2) {
  return window['go']['main']['App']['SearchNotion'](arg1, arg2);
}

export function SearchObsidian(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchObsidian'](arg1, arg2, arg3);
}

export function SearchSessions(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchSessions'](arg1, arg2, arg3);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SetAutoLaunch(arg1) {
  return window['go']['main']['App']['SetAutoLaunch'](arg1);
}

export function SetByokPolicy(arg1) {
  return window['go']['main']['App']['SetByokPolicy'](arg1);
}

export function SetDefaultComboName(arg1) {
  return window['go']['main']['App']['SetDefaultComboName'](arg1);
}

export function SetLocale(arg1) {
  return window['go']['main']['App']['SetLocale'](arg1);
}

export function SetLogRotationConfig(arg1) {
  return window['go']['main']['App']['SetLogRotationConfig'](arg1);
}

export function SetMITMManager(arg1) {
  return window['go']['main']['App']['SetMITMManager'](arg1);
}

export function SetOptimizationConfig(arg1) {
  return window['go']['main']['App']['SetOptimizationConfig'](arg1);
}

export function SetPlatformAPIBaseURL(arg1) {
  return window['go']['main']['App']['SetPlatformAPIBaseURL'](arg1);
}

export function SetRateLimitConfig(arg1) {
  return window['go']['main']['App']['SetRateLimitConfig'](arg1);
}

export function SetSelectedGrant(arg1, arg2) {
  return window['go']['main']['App']['SetSelectedGrant'](arg1, arg2);
}

export function ShowMessage(arg1, arg2) {
  return window['go']['main']['App']['ShowMessage'](arg1, arg2);
}

export function StartLocalGateway() {
  return window['go']['main']['App']['StartLocalGateway']();
}

export function StartMITM() {
  return window['go']['main']['App']['StartMITM']();
}

export function StartOAuthFlow(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartOAuthFlow'](arg1, arg2, arg3, arg4);
}

export function StartTunnel(arg1) {
  return window['go']['main']['App']['StartTunnel'](arg1);
}

export function StopLocalGateway() {
  return window['go']['main']['App']['StopLocalGateway']();
}

export function StopMITM() {
  return window['go']['main']['App']['StopMITM']();
}

export function StopTunnel() {
  return window['go']['main']['App']['StopTunnel']();
}

export function SyncCustomChannelsToCloud(arg1) {
  return window['go']['main']['App']['SyncCustomChannelsToCloud'](arg1);
}

export function SyncLocalDataToCloud() {
  return window['go']['main']['App']['SyncLocalDataToCloud']();
}

export function SyncOptimizationConfigFromCloud() {
  return window['go']['main']['App']['SyncOptimizationConfigFromCloud']();
}

export function SyncOptimizationConfigToCloud() {
  return window['go']['main']['App']['SyncOptimizationConfigToCloud']();
}

export function SyncPlatformChannels() {
  return window['go']['main']['App']['SyncPlatformChannels']();
}

export function SyncPull() {
  return window['go']['main']['App']['SyncPull']();
}

export function SyncPush() {
  return window['go']['main']['App']['SyncPush']();
}

export function TestChannelDirect(arg1) {
  return window['go']['main']['App']['TestChannelDirect'](arg1);
}

export function TestCustomChannel(arg1) {
  return window['go']['main']['App']['TestCustomChannel'](arg1);
}

export function TestMITMDomain(arg1) {
  return window['go']['main']['App']['TestMITMDomain'](arg1);
}

export function ToggleMCPServer(arg1, arg2) {
  return window['go']['main']['App']['ToggleMCPServer'](arg1, arg2);
}

export function TogglePlugin(arg1, arg2) {
  return window['go']['main']['App']['TogglePlugin'](arg1, arg2);
}

export function ToggleSkill(arg1, arg2) {
  return window['go']['main']['App']['ToggleSkill'](arg1, arg2);
}

export function UninstallSkill(arg1) {
  return window['go']['main']['App']['UninstallSkill'](arg1);
}

export function UpdateCloudCombo(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['UpdateCloudCombo'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function UpdateDefaultModel(arg1, arg2) {
  return window['go']['main']['App']['UpdateDefaultModel'](arg1, arg2);
}

export function UpdateRoutingSettings(arg1, arg2) {
  return window['go']['main']['App']['UpdateRoutingSettings'](arg1, arg2);
}

export function UpdateSyncConfig(arg1) {
  return window['go']['main']['App']['UpdateSyncConfig'](arg1);
}

export function VideoGeneration(arg1, arg2, arg3) {
  return window['go']['main']['App']['VideoGeneration'](arg1, arg2, arg3);
}

export function VideoGenerationForChannel(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['VideoGenerationForChannel'](arg1, arg2, arg3, arg4);
}
