// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyComboSortPreset(arg1, arg2) {
  return window['go']['config']['Service']['ApplyComboSortPreset'](arg1, arg2);
}

export function ClearPlatformChannels() {
  return window['go']['config']['Service']['ClearPlatformChannels']();
}

export function DeleteComboTemplate(arg1) {
  return window['go']['config']['Service']['DeleteComboTemplate'](arg1);
}

export function DeleteCustomChannel(arg1) {
  return window['go']['config']['Service']['DeleteCustomChannel'](arg1);
}

export function DeleteModelCombo(arg1) {
  return window['go']['config']['Service']['DeleteModelCombo'](arg1);
}

export function FindComboByModel(arg1) {
  return window['go']['config']['Service']['FindComboByModel'](arg1);
}

export function FirstEnabledChannel(arg1) {
  return window['go']['config']['Service']['FirstEnabledChannel'](arg1);
}

export function GetChannel(arg1) {
  return window['go']['config']['Service']['GetChannel'](arg1);
}

export function GetConfig() {
  return window['go']['config']['Service']['GetConfig']();
}

export function GetDefaultComboName() {
  return window['go']['config']['Service']['GetDefaultComboName']();
}

export function GetModelCombo(arg1) {
  return window['go']['config']['Service']['GetModelCombo'](arg1);
}

export function GetOAuthProviderConfig(arg1) {
  return window['go']['config']['Service']['GetOAuthProviderConfig'](arg1);
}

export function GetOptimizationConfig() {
  return window['go']['config']['Service']['GetOptimizationConfig']();
}

export function GetPlatformAPIBaseURL() {
  return window['go']['config']['Service']['GetPlatformAPIBaseURL']();
}

export function GetRateLimitConfig() {
  return window['go']['config']['Service']['GetRateLimitConfig']();
}

export function GetSelectedGrantID() {
  return window['go']['config']['Service']['GetSelectedGrantID']();
}

export function GetSelectedGrantRelayURL() {
  return window['go']['config']['Service']['GetSelectedGrantRelayURL']();
}

export function GetSetting(arg1) {
  return window['go']['config']['Service']['GetSetting'](arg1);
}

export function ListChannels() {
  return window['go']['config']['Service']['ListChannels']();
}

export function ListComboTemplates() {
  return window['go']['config']['Service']['ListComboTemplates']();
}

export function ListModelCombos() {
  return window['go']['config']['Service']['ListModelCombos']();
}

export function ListOAuthProviderConfigs() {
  return window['go']['config']['Service']['ListOAuthProviderConfigs']();
}

export function NormalizeChannelWeights() {
  return window['go']['config']['Service']['NormalizeChannelWeights']();
}

export function RenameComboTemplate(arg1, arg2) {
  return window['go']['config']['Service']['RenameComboTemplate'](arg1, arg2);
}

export function ReorderChannels(arg1) {
  return window['go']['config']['Service']['ReorderChannels'](arg1);
}

export function ResolveChannelsForModel(arg1) {
  return window['go']['config']['Service']['ResolveChannelsForModel'](arg1);
}

export function ResolvePreferredChannel() {
  return window['go']['config']['Service']['ResolvePreferredChannel']();
}

export function SaveComboTemplate(arg1) {
  return window['go']['config']['Service']['SaveComboTemplate'](arg1);
}

export function SaveCustomChannel(arg1) {
  return window['go']['config']['Service']['SaveCustomChannel'](arg1);
}

export function SaveModelCombo(arg1) {
  return window['go']['config']['Service']['SaveModelCombo'](arg1);
}

export function SaveOAuthProviderConfig(arg1) {
  return window['go']['config']['Service']['SaveOAuthProviderConfig'](arg1);
}

export function SetAnalyticsEnabled(arg1) {
  return window['go']['config']['Service']['SetAnalyticsEnabled'](arg1);
}

export function SetAutoLaunch(arg1) {
  return window['go']['config']['Service']['SetAutoLaunch'](arg1);
}

export function SetDefaultComboName(arg1) {
  return window['go']['config']['Service']['SetDefaultComboName'](arg1);
}

export function SetDefaultModel(arg1, arg2) {
  return window['go']['config']['Service']['SetDefaultModel'](arg1, arg2);
}

export function SetOptimizationConfig(arg1) {
  return window['go']['config']['Service']['SetOptimizationConfig'](arg1);
}

export function SetPlatformAPIBaseURL(arg1) {
  return window['go']['config']['Service']['SetPlatformAPIBaseURL'](arg1);
}

export function SetRateLimitConfig(arg1) {
  return window['go']['config']['Service']['SetRateLimitConfig'](arg1);
}

export function SetSelectedGrant(arg1, arg2) {
  return window['go']['config']['Service']['SetSelectedGrant'](arg1, arg2);
}

export function UpdateChannelHealth(arg1, arg2) {
  return window['go']['config']['Service']['UpdateChannelHealth'](arg1, arg2);
}

export function UpdateChannelModels(arg1, arg2) {
  return window['go']['config']['Service']['UpdateChannelModels'](arg1, arg2);
}

export function UpdateRoutingSettings(arg1, arg2) {
  return window['go']['config']['Service']['UpdateRoutingSettings'](arg1, arg2);
}

export function UpdateSetting(arg1, arg2) {
  return window['go']['config']['Service']['UpdateSetting'](arg1, arg2);
}

export function UpsertPlatformChannels(arg1) {
  return window['go']['config']['Service']['UpsertPlatformChannels'](arg1);
}

export function ValidateChannelWeights() {
  return window['go']['config']['Service']['ValidateChannelWeights']();
}
