// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function ApplyComboSortPreset(arg1:string,arg2:string):Promise<void>;

export function ClearPlatformChannels():Promise<void>;

export function DeleteComboTemplate(arg1:string):Promise<void>;

export function DeleteCustomChannel(arg1:string):Promise<void>;

export function DeleteModelCombo(arg1:string):Promise<void>;

export function FindComboByModel(arg1:string):Promise<config.ModelCombo>;

export function FirstEnabledChannel(arg1:string):Promise<config.Channel|boolean>;

export function GetChannel(arg1:string):Promise<config.Channel|boolean>;

export function GetConfig():Promise<config.AppConfig>;

export function GetDefaultComboName():Promise<string>;

export function GetModelCombo(arg1:string):Promise<config.ModelCombo|boolean>;

export function GetOAuthProviderConfig(arg1:string):Promise<config.OAuthProviderConfig|boolean>;

export function GetOptimizationConfig():Promise<config.OptimizationConfig>;

export function GetPlatformAPIBaseURL():Promise<string>;

export function GetRateLimitConfig():Promise<config.RateLimitConfig>;

export function GetSelectedGrantID():Promise<string>;

export function GetSelectedGrantRelayURL():Promise<string>;

export function GetSetting(arg1:string):Promise<string>;

export function ListChannels():Promise<Array<config.Channel>>;

export function ListComboTemplates():Promise<Array<config.ModelCombo>>;

export function ListModelCombos():Promise<Array<config.ModelCombo>>;

export function ListOAuthProviderConfigs():Promise<Array<config.OAuthProviderConfig>>;

export function NormalizeChannelWeights():Promise<Array<string>>;

export function RenameComboTemplate(arg1:string,arg2:string):Promise<void>;

export function ReorderChannels(arg1:Array<string>):Promise<void>;

export function ResolveChannelsForModel(arg1:string):Promise<Array<config.Channel>|string>;

export function ResolvePreferredChannel():Promise<config.Channel|boolean>;

export function SaveComboTemplate(arg1:config.ModelCombo):Promise<void>;

export function SaveCustomChannel(arg1:config.Channel):Promise<string>;

export function SaveModelCombo(arg1:config.ModelCombo):Promise<void>;

export function SaveOAuthProviderConfig(arg1:config.OAuthProviderConfig):Promise<void>;

export function SetAnalyticsEnabled(arg1:boolean):Promise<void>;

export function SetAutoLaunch(arg1:boolean):Promise<void>;

export function SetDefaultComboName(arg1:string):Promise<void>;

export function SetDefaultModel(arg1:string,arg2:string):Promise<void>;

export function SetOptimizationConfig(arg1:config.OptimizationConfig):Promise<void>;

export function SetPlatformAPIBaseURL(arg1:string):Promise<void>;

export function SetRateLimitConfig(arg1:config.RateLimitConfig):Promise<void>;

export function SetSelectedGrant(arg1:string,arg2:string):Promise<void>;

export function UpdateChannelHealth(arg1:string,arg2:string):Promise<void>;

export function UpdateChannelModels(arg1:string,arg2:Array<string>):Promise<void>;

export function UpdateRoutingSettings(arg1:string,arg2:number):Promise<void>;

export function UpdateSetting(arg1:string,arg2:any):Promise<void>;

export function UpsertPlatformChannels(arg1:Array<config.Channel>):Promise<void>;

export function ValidateChannelWeights():Promise<void>;
