// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function InstallFromGitHub(arg1, arg2) {
  return window['go']['skills']['Service']['InstallFromGitHub'](arg1, arg2);
}

export function InstallFromLocal(arg1, arg2) {
  return window['go']['skills']['Service']['InstallFromLocal'](arg1, arg2);
}

export function ListSkills() {
  return window['go']['skills']['Service']['ListSkills']();
}

export function ScanSkillsDir() {
  return window['go']['skills']['Service']['ScanSkillsDir']();
}

export function ToggleSkill(arg1, arg2) {
  return window['go']['skills']['Service']['ToggleSkill'](arg1, arg2);
}

export function UninstallSkill(arg1) {
  return window['go']['skills']['Service']['UninstallSkill'](arg1);
}
