// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {skills} from '../models';

export function InstallFromGitHub(arg1:string,arg2:string):Promise<void>;

export function InstallFromLocal(arg1:string,arg2:string):Promise<void>;

export function ListSkills():Promise<Array<skills.Skill>>;

export function ScanSkillsDir():Promise<Array<skills.Skill>>;

export function ToggleSkill(arg1:string,arg2:boolean):Promise<void>;

export function UninstallSkill(arg1:string):Promise<void>;
