// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearLogs() {
  return window['go']['logs']['Service']['ClearLogs']();
}

export function ListLogs(arg1, arg2) {
  return window['go']['logs']['Service']['ListLogs'](arg1, arg2);
}

export function ListLogsFiltered(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['logs']['Service']['ListLogsFiltered'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function RecordLog(arg1) {
  return window['go']['logs']['Service']['RecordLog'](arg1);
}
