// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {logs} from '../models';

export function ClearLogs():Promise<void>;

export function GetIntentScenarioStats():Promise<Array<Record<string, any>>>;

export function ListLogs(arg1:number,arg2:number):Promise<Array<logs.RequestLog>>;

export function ListLogsFiltered(arg1:number,arg2:number,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<Array<logs.RequestLog>>;

export function RecordLog(arg1:logs.RequestLog):Promise<void>;
