// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gateway} from '../models';
import {usage} from '../models';
import {context} from '../models';

export function GetComboRouteMetrics():Promise<Array<gateway.ComboRouteMetrics>>;

export function GetConcurrencyInflight(arg1:string):Promise<number>;

export function GetListenPort():Promise<number>;

export function IsRunning():Promise<boolean>;

export function ResetComboRouteMetrics():Promise<void>;

export function ServeGatewayRequest(arg1:string,arg2:Array<number>,arg3:string):Promise<number|Array<number>>;

export function SetAccessToken(arg1:string):Promise<void>;

export function SetRTKConfig(arg1:boolean,arg2:number):Promise<void>;

export function SetUsageService(arg1:usage.Service):Promise<void>;

export function Start(arg1:context.Context):Promise<void>;

export function Stop():Promise<void>;

export function SyncChannelConcurrencyLimits():Promise<void>;
