// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetComboRouteMetrics() {
  return window['go']['gateway']['Service']['GetComboRouteMetrics']();
}

export function GetConcurrencyInflight(arg1) {
  return window['go']['gateway']['Service']['GetConcurrencyInflight'](arg1);
}

export function GetListenPort() {
  return window['go']['gateway']['Service']['GetListenPort']();
}

export function IsRunning() {
  return window['go']['gateway']['Service']['IsRunning']();
}

export function ResetComboRouteMetrics() {
  return window['go']['gateway']['Service']['ResetComboRouteMetrics']();
}

export function ServeGatewayRequest(arg1, arg2, arg3) {
  return window['go']['gateway']['Service']['ServeGatewayRequest'](arg1, arg2, arg3);
}

export function SetAccessToken(arg1) {
  return window['go']['gateway']['Service']['SetAccessToken'](arg1);
}

export function SetRTKConfig(arg1, arg2) {
  return window['go']['gateway']['Service']['SetRTKConfig'](arg1, arg2);
}

export function SetUsageService(arg1) {
  return window['go']['gateway']['Service']['SetUsageService'](arg1);
}

export function Start(arg1) {
  return window['go']['gateway']['Service']['Start'](arg1);
}

export function Stop() {
  return window['go']['gateway']['Service']['Stop']();
}

export function SyncChannelConcurrencyLimits() {
  return window['go']['gateway']['Service']['SyncChannelConcurrencyLimits']();
}
