// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteSession(arg1, arg2) {
  return window['go']['sessions']['Service']['DeleteSession'](arg1, arg2);
}

export function GetMessages(arg1, arg2) {
  return window['go']['sessions']['Service']['GetMessages'](arg1, arg2);
}

export function GetSession(arg1, arg2) {
  return window['go']['sessions']['Service']['GetSession'](arg1, arg2);
}

export function ListSessions(arg1, arg2) {
  return window['go']['sessions']['Service']['ListSessions'](arg1, arg2);
}

export function SearchSessions(arg1, arg2, arg3) {
  return window['go']['sessions']['Service']['SearchSessions'](arg1, arg2, arg3);
}
