// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {sessions} from '../models';

export function DeleteSession(arg1:string,arg2:string):Promise<void>;

export function GetMessages(arg1:string,arg2:string):Promise<Array<sessions.Message>>;

export function GetSession(arg1:string,arg2:string):Promise<sessions.Session>;

export function ListSessions(arg1:string,arg2:number):Promise<Array<sessions.Session>>;

export function SearchSessions(arg1:string,arg2:string,arg3:number):Promise<Array<sessions.Session>>;
