// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {usage} from '../models';

export function GetAllRecords():Promise<Array<usage.UsageRecord>>;

export function GetDailyUsage(arg1:number):Promise<Array<usage.DailyUsage>>;

export function GetModelStats():Promise<Array<usage.ModelStatsEntry>>;

export function GetTotalUsage():Promise<Record<string, any>>;

export function GetUsageSummary():Promise<usage.UsageSummary>;

export function ListPricing():Promise<Array<usage.ModelPricing>>;

export function PurgeBefore(arg1:number):Promise<number>;

export function RecordUsage(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<void>;

export function RecordUsageV2(arg1:usage.UsageDetail):Promise<void>;

export function SavePricing(arg1:Array<usage.ModelPricing>):Promise<void>;

export function SetModelStatsFromCloud(arg1:Array<usage.ModelStatsEntry>):Promise<void>;
