// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllRecords() {
  return window['go']['usage']['Service']['GetAllRecords']();
}

export function GetDailyUsage(arg1) {
  return window['go']['usage']['Service']['GetDailyUsage'](arg1);
}

export function GetModelStats() {
  return window['go']['usage']['Service']['GetModelStats']();
}

export function GetTotalUsage() {
  return window['go']['usage']['Service']['GetTotalUsage']();
}

export function GetUsageSummary() {
  return window['go']['usage']['Service']['GetUsageSummary']();
}

export function ListPricing() {
  return window['go']['usage']['Service']['ListPricing']();
}

export function PurgeBefore(arg1) {
  return window['go']['usage']['Service']['PurgeBefore'](arg1);
}

export function RecordUsage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['usage']['Service']['RecordUsage'](arg1, arg2, arg3, arg4, arg5);
}

export function RecordUsageV2(arg1) {
  return window['go']['usage']['Service']['RecordUsageV2'](arg1);
}

export function SavePricing(arg1) {
  return window['go']['usage']['Service']['SavePricing'](arg1);
}

export function SetModelStatsFromCloud(arg1) {
  return window['go']['usage']['Service']['SetModelStatsFromCloud'](arg1);
}
