// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {prompts} from '../models';

export function ApplyPreset(arg1:string,arg2:string):Promise<void>;

export function DeletePreset(arg1:string,arg2:string):Promise<void>;

export function ListPresets():Promise<Array<prompts.PromptPreset>>;

export function ReadCurrentPrompt(arg1:string):Promise<string>;

export function SavePreset(arg1:prompts.PromptPreset):Promise<void>;
