// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyPreset(arg1, arg2) {
  return window['go']['prompts']['Service']['ApplyPreset'](arg1, arg2);
}

export function DeletePreset(arg1, arg2) {
  return window['go']['prompts']['Service']['DeletePreset'](arg1, arg2);
}

export function ListPresets() {
  return window['go']['prompts']['Service']['ListPresets']();
}

export function ReadCurrentPrompt(arg1) {
  return window['go']['prompts']['Service']['ReadCurrentPrompt'](arg1);
}

export function SavePreset(arg1) {
  return window['go']['prompts']['Service']['SavePreset'](arg1);
}
